site_name: Cycle-canceling algorithm
site_url: https://cyclecanceling.cedoor.dev
site_description: TypeScript implementation of cycle-canceling algorithm.
site_author: Omar Desogus
copyright: Copyright (c) 2020 <a href="https://cedoor.dev" target="_blank">Omar Desogus</a>

extra:
  support:
    email: me@cedoor.dev
    website: https://cyclecanceling.cedoor.dev
  search:
    language: 'en'
    tokenizer: '[\s]+'

repo_name: cedoor/cycle-canceling
repo_url: https://github.com/cedoor/cycle-canceling

theme:
  name: material
  palette:
    primary: blue-grey
    accent: teal
nav:
  - README: README.md
  - API: globals.md

plugins:
  - search
