language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '12'
script:
  - npm run test:prod && npm run build
after_success:
  - npm run travis-deploy-once "npm run report-coverage"
  - if [ "$TRAVIS_BRANCH" = "main" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run travis-deploy-once "npm run docs:publish"; fi
branches:
  only:
    main
