language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '12'
  - '14'
before_script:
script:
  - yarn run lint && yarn run test
after_success:
install:
  - yarn install
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
