name: docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - run: yarn --frozen-lockfile
    - run: yarn docs
    
    - name: Github Pages 
      uses: crazy-max/ghaction-github-pages@v2.2.0
      with:
        build_dir: docs
        commit_message: "docs: update documentation website"
        fqdn: nfa.cedoor.dev
        jekyll: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
